export const kidsOrderStructure = [
  { length: 18, pieces: 0 },
  { length: 20, pieces: 0 },
  { length: 22, pieces: 0 },
  { length: 26, pieces: 0 },
  { length: 28, pieces: 0 },
];

export const boysOrderStructure = [
  { length: 30, pieces: 0 },
  { length: 32, pieces: 0 },
  { length: 34, pieces: 0 },
  { length: 36, pieces: 0 },
  { length: 38, pieces: 0 },
  { length: 40, pieces: 0 },
  { length: 42, pieces: 0 },
  { length: 44, pieces: 0 },
  { length: 46, pieces: 0 },
  { length: 48, pieces: 0 },
  { length: 50, pieces: 0 },
];

export const menOrderStructure = [
  { size: "s", length: 52, pieces: 0 },
  { size: "s", length: 54, pieces: 0 },
  { size: "s", length: 56, pieces: 0 },
  { size: "s", length: 58, pieces: 0 },
  { size: "s", length: 60, pieces: 0 },
  { size: "s", length: 62, pieces: 0 },
  { size: "m", length: 52, pieces: 0 },
  { size: "m", length: 54, pieces: 0 },
  { size: "m", length: 56, pieces: 0 },
  { size: "m", length: 58, pieces: 0 },
  { size: "m", length: 60, pieces: 0 },
  { size: "m", length: 62, pieces: 0 },
  { size: "l", length: 52, pieces: 0 },
  { size: "l", length: 54, pieces: 0 },
  { size: "l", length: 56, pieces: 0 },
  { size: "l", length: 58, pieces: 0 },
  { size: "l", length: 60, pieces: 0 },
  { size: "l", length: 62, pieces: 0 },
  { size: "xl", length: 52, pieces: 0 },
  { size: "xl", length: 54, pieces: 0 },
  { size: "xl", length: 56, pieces: 0 },
  { size: "xl", length: 58, pieces: 0 },
  { size: "xl", length: 60, pieces: 0 },
  { size: "xl", length: 62, pieces: 0 },
  { size: "xxl", length: 52, pieces: 0 },
  { size: "xxl", length: 54, pieces: 0 },
  { size: "xxl", length: 56, pieces: 0 },
  { size: "xxl", length: 58, pieces: 0 },
  { size: "xxl", length: 60, pieces: 0 },
  { size: "xxl", length: 62, pieces: 0 },
  { size: "xxxl", length: 52, pieces: 0 },
  { size: "xxxl", length: 54, pieces: 0 },
  { size: "xxxl", length: 56, pieces: 0 },
  { size: "xxxl", length: 58, pieces: 0 },
  { size: "xxxl", length: 60, pieces: 0 },
  { size: "xxxl", length: 62, pieces: 0 },
];
